# Generated by Django 5.1.2 on 2024-10-30 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contact_info', models.CharField(max_length=100, unique=True)),
                ('web_site', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('hire_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('birthday_date', models.DateField()),
            ],
            options={
                'db_table': 'employee',
                'constraints': [models.CheckConstraint(condition=models.Q(('salary__gte', 0)), name='check_salary_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacyApp.customer')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('pharmacy_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('contact_info', models.CharField(max_length=250, unique=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacyApp.company')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacyApp.employee')),
            ],
            options={
                'db_table': 'pharmacy',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('amount_in_receipt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=255)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacyApp.order')),
            ],
            options={
                'db_table': 'receipt',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('quantity_in_stock', models.IntegerField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(max_length=255)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacyApp.supplier')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_of_transaction', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=55)),
                ('receipt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacyApp.receipt')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('pharmacy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacyApp.pharmacy')),
            ],
            options={
                'db_table': 'warehouse',
            },
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('warehouse_stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacyApp.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacyApp.warehouse')),
            ],
            options={
                'db_table': 'warehouse_stock',
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('receipt_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('receipt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacyApp.receipt')),
                ('warehouse_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacyApp.warehousestock')),
            ],
            options={
                'db_table': 'receipt_item',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacyApp.warehousestock'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_in_stock__gte', 0)), name='check_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='warehousestock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='check_stock_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='warehousestock',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='check_stock_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='receiptitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='check_quantity_positive'),
        ),
    ]
