# Generated by Django 5.1.2 on 2024-11-11 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptitem',
            name='warehouse_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacyApp.warehousestock'),
        ),
    ]
