# Generated by Django 5.1.2 on 2024-11-11 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyApp', '0002_alter_receiptitem_warehouse_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptitem',
            name='receipt_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacyApp.receipt'),
        ),
    ]
